### ISSUE TITLE
Doesn't work with Alpine

### ISSUE THREAD

**Issue by awebeer256** [jeanp413/open-remote-wsl#3]
I can successfully "open remote" with Ubuntu as the WSL distro, but not with Alpine.

<details><summary>Output in VSCodium</summary>

```
[Info  - <timestamp>] Resolving wsl remote authority 'wsl+Alpine' (attemp #1)
[Trace  - <timestamp>] Running WSL command: wsl.exe --distribution Alpine -- bash -c '
# Server installation script
```
(Snip)
```
'
[Trace  - <timestamp>] Server install command stdout:
Server script already installed in /home/<username>/.vscodium-server/bin/13ae69686c4390a9aee7b71b44337eb488319f26/bin/codium-server
Error server did not start sucessfully
158166ff6915dee1ef770c20: start
exitCode==1==
listeningOn====
connectionToken==f78c74a6-efe9-48d5-918d-fcc29b824364==
logFile==/home/<username>/.vscodium-server/.13ae69686c4390a9aee7b71b44337eb488319f26.log==
osReleaseId==alpine==
arch==x86_64==
platform==Linux==
tmpDir==/mnt/wslg/runtime-dir==
158166ff6915dee1ef770c20: end

[Error  - <timestamp>] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (c:\Users\<username>\.vscode-oss\extensions\jeanp413.open-remote-wsl-0.0.4-universal\out\extension.js:1:26854)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async c:\Users\<username>\.vscode-oss\extensions\jeanp413.open-remote-wsl-0.0.4-universal\out\extension.js:1:1801
```
</details>

<details><summary>Log file</summary>

`~/.vscodium-server/.13ae69686c4390a9aee7b71b44337eb488319f26.log`

```
/home/<username>/.vscodium-server/bin/13ae69686c4390a9aee7b71b44337eb488319f26/bin/codium-server: line 12: /home/<username>/.vscodium-server/bin/13ae69686c4390a9aee7b71b44337eb488319f26/node: not found
```
</details>

Looks like the `node` binary is trying to call something else that it's expecting to be installed as part of the Linux distro, but whatever it is isn't included with Alpine by default.

Windows 10 22H2, x86_64
VSCodium 1.82.0
Alpine 3.17

**Comment by jeanp413** [comment]
Upstream issue in vscodium https://github.com/VSCodium/vscodium/issues/1634
