### ISSUE TITLE
Will error connecting to WSL target the second time and beyond

### ISSUE THREAD

**Issue by orariley70** [jeanp413/open-remote-wsl#4]
Steps:
1. Install clean WSL distro (official Canonical Ubuntu distribution from Microsoft Store), the extension (0.0.4), VSCodium (1.85.1)
2. Open target in WSL, then let the vscodium-server install.
3. After server installation complete, exit VSCodium completely
4. Issue `wsl --shutdown` at cmd
5. Open VSCodium again, try connecting to WSL again

Expected: VSCodium will find existing vscodium-server install and connect per usual.
Actual: VSCodium errors out with these messages. Clicking "Retry" will error out again. To fix the issue I have to type `rm -rf ~/.vscodium-server/bin`. The fix will work until next time WSL is started from cold boot again, then I need to fix the issue again.
The log file `/home/ubuntu/.vscodium-server/.08e6c15293922dd53a864bb041be381322fee401.log` is zero bytes in length.

```
[Window Title]
VSCodium

[Content]
Could not establish connection to WSL distro "Ubuntu"

[Close Remote] [Retry] [Cancel]
```
```

[Trace  - 10:02:13.755] Server install command stdout:
Server script already installed in /home/ubuntu/.vscodium-server/bin/08e6c15293922dd53a864bb041be381322fee401/bin/codium-server
Error server did not start sucessfully
2a175f5c1b172c3a4ad2faed: start
exitCode==1==
listeningOn====
connectionToken==27061a73-aab5-45fa-b372-8cfc429875f5==
logFile==/home/ubuntu/.vscodium-server/.08e6c15293922dd53a864bb041be381322fee401.log==
osReleaseId==ubuntu==
arch==x86_64==
platform==Linux==
tmpDir==/run/user/1000/==
2a175f5c1b172c3a4ad2faed: end

[Error  - 10:02:13.755] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (c:\Users\User\.vscode-oss\extensions\jeanp413.open-remote-wsl-0.0.4-universal\out\extension.js:1:26854)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async c:\Users\User\.vscode-oss\extensions\jeanp413.open-remote-wsl-0.0.4-universal\out\extension.js:1:1801
```

VSCodium version information:
```
[Window Title]
VSCodium

[Main Instruction]
VSCodium

[Content]

Version: 1.85.1 (system setup)
Release: 23348
Commit: 08e6c15293922dd53a864bb041be381322fee401
Date: 2023-12-14T20:44:42.949Z (3 wks ago)
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

[Copy] [OK]
```

**Comment by orariley70** [comment]
I'm not sure how to collect logs during script installation, or even execute the script manually on the WSL Terminal.

**Comment by PylotLight** [comment]
duplicate of https://github.com/jeanp413/open-remote-wsl/issues/2
