### ISSUE TITLE
NixOS not detected as Linux distro

### ISSUE THREAD

**Issue by eku** [jeanp413/open-remote-wsl#7]
I'm running [NixOS](https://nixos.org/)  Linux distro in WSL2.

Needless to say, Microsoft's combination of VSCode and Remote WSL works with it.

VSCodium and Open Remote WSL, on the other hand, abort with an error.

<details>
  <summary>Logs</summary>

[Trace  - 07:31:26.508] Server install command stdout:
Error platform not supported: 
d3289fc916cdbbd8c96e294d: start
exitCode==1==
listeningOn====
connectionToken====
logFile==/home/wsl/.vscodium-server/.c8a36a69377856369f139f39ee56dd3838130fbf.log==
osReleaseId====
arch====
platform====
tmpDir==/run/user/1000/==
d3289fc916cdbbd8c96e294d: end

[Error  - 07:31:26.509] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (c:\Users\XXX\.vscode-oss\extensions\jeanp413.open-remote-wsl-0.0.4\out\extension.js:1:26881)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async c:\Users\XXX\.vscode-oss\extensions\jeanp413.open-remote-wsl-0.0.4\out\extension.js:1:1801

</details>

By the way, the log file `/home/wsl/.vscodium-server/.c8a36a69377856369f139f39ee56dd3838130fbf.log` mentioned in the log does not exist.

**Comment by GitMensch** [comment]
This is the place where the platform is checked: https://github.com/jeanp413/open-remote-wsl/blob/20824d50a3346f5fbd7875d3319a1445d8dc1c1e/src/serverSetup.ts#L179-L189
as you see the output - which is empty in your case - is the result of `uname -s` and there are known issues with that on NixOS -you even have a package to solve this issue: https://mynixos.com/nixpkgs/package/deterministic-uname I _guess_ that as soon as you install that the setup will work.

**Comment by GitMensch** [comment]
ping @eku about NixOS' uname issues (you seem to have a running WSL instance of that...)

**Comment by eku** [comment]
> ping [@eku](https://github.com/eku) about NixOS' uname issues (you seem to have a running WSL instance of that...)

```
$ uname -a
Linux wsl 6.18.33.2-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Thu Jun 18 21:54:43 UTC 2026 x86_64 GNU/Linux
```

**Comment by GitMensch** [comment]
... and `uname -s` which is used in the script (plus output of `echo $OSTYPE`)?

**Comment by eku** [comment]
> ... and `uname -s` which is used in the script (plus output of `echo $OSTYPE`)?

```
$ uname -s
Linux
$ echo $OSTYPE
linux-gnu
```

**Comment by GitMensch** [comment]
Then I see no reason that this shouldn't work (at least not in the detection code), you may want to recheck (note: the newer version of this extension since your issue-creation has no change to that, so I _guess_ your NixOS installation now reports something different , or you've installed [deterministic-uname](https://mynixos.com/nixpkgs/package/deterministic-uname) or something similar).
