### ISSUE TITLE
Open Remote - WSL not working on my windows system with debian distro

### ISSUE THREAD

**Issue by SnoepNFTs** [jeanp413/open-remote-wsl#8]
### Hello, I am encountering this issue everytime I am trying to connect to WSL using your vscodium extension. 

<details> 
<summary>
<strong> This is the output it shows after it fails </strong> 
</summary>

![image](https://github.com/jeanp413/open-remote-wsl/assets/128747388/3b0cdf5b-3f1a-4f1b-9951-b036ea1d7a06)

```
[Info  - 14:28:18.780] Resolving wsl remote authority 'wsl+Debian' (attemp #1)
[Trace  - 14:28:18.783] Running WSL command: wsl.exe --distribution Debian -- bash -c '
# Server installation script

TMP_DIR="${XDG_RUNTIME_DIR:-"/tmp"}"

DISTRO_VERSION="1.89.1"
DISTRO_COMMIT="a045dcfceda27f896936bfd8cbf524f6a93a2f46"
DISTRO_QUALITY="stable"
DISTRO_VSCODIUM_RELEASE="24130"

SERVER_APP_NAME="codium-server"
SERVER_INITIAL_EXTENSIONS=""
SERVER_LISTEN_FLAG="--port=0"
SERVER_DATA_DIR="$HOME/.vscodium-server"
SERVER_DIR="$SERVER_DATA_DIR/bin/$DISTRO_COMMIT"
SERVER_SCRIPT="$SERVER_DIR/bin/$SERVER_APP_NAME"
SERVER_LOGFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.log"
SERVER_PIDFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.pid"
SERVER_TOKENFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.token"
SERVER_OS=
SERVER_ARCH=
SERVER_CONNECTION_TOKEN=
SERVER_DOWNLOAD_URL=

LISTENING_ON=
OS_RELEASE_ID=
ARCH=
PLATFORM=

# Mimic output from logs of remote-ssh extension
print_install_results_and_exit() {
    echo "cf9415c8e5f51ae208730c95: start"
    echo "exitCode==$1=="
    echo "listeningOn==$LISTENING_ON=="
    echo "connectionToken==$SERVER_CONNECTION_TOKEN=="
    echo "logFile==$SERVER_LOGFILE=="
    echo "osReleaseId==$OS_RELEASE_ID=="
    echo "arch==$ARCH=="
    echo "platform==$PLATFORM=="
    echo "tmpDir==$TMP_DIR=="
    
    echo "cf9415c8e5f51ae208730c95: end"
    exit 0
}

# Check if platform is supported
PLATFORM="$(uname -s)"
case $PLATFORM in
    Linux)
        SERVER_OS="linux"
        ;;
    *)
        echo "Error platform not supported: $PLATFORM"
        print_install_results_and_exit 1
        ;;
esac

# Check machine architecture
ARCH="$(uname -m)"
case $ARCH in
    x86_64 | amd64)
        SERVER_ARCH="x64"
        ;;
    armv7l | armv8l)
        SERVER_ARCH="armhf"
        ;;
    arm64 | aarch64)
        SERVER_ARCH="arm64"
        ;;
    *)
        echo "Error architecture not supported: $ARCH"
        print_install_results_and_exit 1
        ;;
esac

# https://www.freedesktop.org/software/systemd/man/os-release.html
OS_RELEASE_ID="$(grep -i '\''^ID='\'' /etc/os-release 2>/dev/null | sed '\''s/^ID=//gi'\'' | sed '\''s/"//g'\'')"
if [[ -z $OS_RELEASE_ID ]]; then
    OS_RELEASE_ID="$(grep -i '\''^ID='\'' /usr/lib/os-release 2>/dev/null | sed '\''s/^ID=//gi'\'' | sed '\''s/"//g'\'')"
    if [[ -z $OS_RELEASE_ID ]]; then
        OS_RELEASE_ID="unknown"
    fi
fi

# Create installation folder
if [[ ! -d $SERVER_DIR ]]; then
    mkdir -p $SERVER_DIR
    if (( $? > 0 )); then
        echo "Error creating server install directory"
        print_install_results_and_exit 1
    fi
fi

SERVER_DOWNLOAD_URL="$(echo "https://github.com/VSCodium/vscodium/releases/download/\${version}.\${release}/vscodium-reh-\${os}-\${arch}-\${version}.\${release}.tar.gz" | sed "s/\${quality}/$DISTRO_QUALITY/g" | sed "s/\${version}/$DISTRO_VERSION/g" | sed "s/\${commit}/$DISTRO_COMMIT/g" | sed "s/\${os}/$SERVER_OS/g" | sed "s/\${arch}/$SERVER_ARCH/g" | sed "s/\${release}/$DISTRO_VSCODIUM_RELEASE/g")"

# Check if server script is already installed
if [[ ! -f $SERVER_SCRIPT ]]; then
    if [[ "$SERVER_OS" = "dragonfly" ]] || [[ "$SERVER_OS" = "freebsd" ]]; then
        echo "Error "$SERVER_OS" needs manual installation of remote extension host"
        print_install_results_and_exit 1
    fi

    pushd $SERVER_DIR > /dev/null

    if [[ ! -z $(which wget) ]]; then
        wget --tries=3 --timeout=10 --continue --no-verbose -O vscode-server.tar.gz $SERVER_DOWNLOAD_URL
    elif [[ ! -z $(which curl) ]]; then
        curl --retry 3 --connect-timeout 10 --location --show-error --silent --output vscode-server.tar.gz $SERVER_DOWNLOAD_URL
    else
        echo "Error no tool to download server binary"
        print_install_results_and_exit 1
    fi

    if (( $? > 0 )); then
        echo "Error downloading server from $SERVER_DOWNLOAD_URL"
        print_install_results_and_exit 1
    fi

    tar -xf vscode-server.tar.gz --strip-components 1
    if (( $? > 0 )); then
        echo "Error while extracting server contents"
        print_install_results_and_exit 1
    fi

    if [[ ! -f $SERVER_SCRIPT ]]; then
        echo "Error server contents are corrupted"
        print_install_results_and_exit 1
    fi

    rm -f vscode-server.tar.gz

    popd > /dev/null
else
    echo "Server script already installed in $SERVER_SCRIPT"
fi

# Try to find if server is already running
if [[ -f $SERVER_PIDFILE ]]; then
    SERVER_PID="$(cat $SERVER_PIDFILE)"
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -p $SERVER_PID | grep $SERVER_SCRIPT)"
else
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -A | grep $SERVER_SCRIPT | grep -v grep)"
fi

if [[ -z $SERVER_RUNNING_PROCESS ]]; then
    if [[ -f $SERVER_LOGFILE ]]; then
        rm $SERVER_LOGFILE
    fi
    if [[ -f $SERVER_TOKENFILE ]]; then
        rm $SERVER_TOKENFILE
    fi

    touch $SERVER_TOKENFILE
    chmod 600 $SERVER_TOKENFILE
    SERVER_CONNECTION_TOKEN="7141ea9d-eeb8-452f-8a1a-c40ad4f33fb5"
    echo $SERVER_CONNECTION_TOKEN > $SERVER_TOKENFILE

    $SERVER_SCRIPT --start-server --host=127.0.0.1 $SERVER_LISTEN_FLAG $SERVER_INITIAL_EXTENSIONS --connection-token-file $SERVER_TOKENFILE --telemetry-level off --use-host-proxy --disable-websocket-compression --without-browser-env-var --enable-remote-auto-shutdown --accept-server-license-terms &> $SERVER_LOGFILE &
    echo $! > $SERVER_PIDFILE
else
    echo "Server script is already running $SERVER_SCRIPT"
fi

if [[ -f $SERVER_TOKENFILE ]]; then
    SERVER_CONNECTION_TOKEN="$(cat $SERVER_TOKENFILE)"
else
    echo "Error server token file not found $SERVER_TOKENFILE"
    print_install_results_and_exit 1
fi

if [[ -f $SERVER_LOGFILE ]]; then
    for i in {1..5}; do
        LISTENING_ON="$(cat $SERVER_LOGFILE | grep -E '\''Extension host agent listening on .+'\'' | sed '\''s/Extension host agent listening on //'\'')"
        if [[ -n $LISTENING_ON ]]; then
            break
        fi
        sleep 0.5
    done

    if [[ -z $LISTENING_ON ]]; then
        echo "Error server did not start sucessfully"
        print_install_results_and_exit 1
    fi
else
    echo "Error server log file not found $SERVER_LOGFILE"
    print_install_results_and_exit 1
fi

# Finish server setup and keep script running
if [[ -z $SERVER_RUNNING_PROCESS ]]; then
    echo "cf9415c8e5f51ae208730c95: start"
    echo "exitCode==0=="
    echo "listeningOn==$LISTENING_ON=="
    echo "connectionToken==$SERVER_CONNECTION_TOKEN=="
    echo "logFile==$SERVER_LOGFILE=="
    echo "osReleaseId==$OS_RELEASE_ID=="
    echo "arch==$ARCH=="
    echo "platform==$PLATFORM=="
    echo "tmpDir==$TMP_DIR=="
    
    echo "cf9415c8e5f51ae208730c95: end"

    echo "cf9415c8e5f51ae208730c95: Server installation script done"

    SERVER_PID="$(cat $SERVER_PIDFILE)"
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -p $SERVER_PID | grep $SERVER_SCRIPT)"
    while [[ -n $SERVER_RUNNING_PROCESS ]]; do
        sleep 300;
        SERVER_RUNNING_PROCESS="$(ps -o pid,args -p $SERVER_PID | grep $SERVER_SCRIPT)"
    done
else
    print_install_results_and_exit 0
fi
'
[Trace  - 14:28:32.600] Server install command stdout:
Error downloading server from https://github.com/VSCodium/vscodium/releases/download/1.89.1.24130/vscodium-reh-linux-x64-1.89.1.24130.tar.gz
cf9415c8e5f51ae208730c95: start
exitCode==1==
listeningOn====
connectionToken====
logFile==/home/snoep/.vscodium-server/.a045dcfceda27f896936bfd8cbf524f6a93a2f46.log==
osReleaseId==debian==
arch==x86_64==
platform==Linux==
tmpDir==/mnt/wslg/runtime-dir==
cf9415c8e5f51ae208730c95: end

[Error  - 14:28:32.600] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (c:\Users\Ezza\.vscode-oss\extensions\jeanp413.open-remote-wsl-0.0.4-universal\out\extension.js:1:26854)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async c:\Users\Ezza\.vscode-oss\extensions\jeanp413.open-remote-wsl-0.0.4-universal\out\extension.js:1:1801
```
</details>

<p> I really need vscodium to work as it is required for a course that I am following. 
I transitioned into vscodium as I learned its benefits over vscode. But currently I am unsure if there is a fix for this?
If there isn't could someone clarify this for me so that I can transition back to vscode (at least for in the short term)
</p>

**Comment by GitMensch** [comment]
Please VSCodium, then try again report back. The error is noted as being a download error (sadly we still don't output any details). and I _guess_ you wget/curl from WSL using URLs.

**Comment by SnoepNFTs** [comment]
> Please VSCodium, then try again report back. The error is noted as being a download error (sadly we still don't output any details). and I _guess_ you can wget/curl from WSL using URLs.

Thanks for your reply, yeah I figured a long while ago to just go back to standard vscode for now.

**Comment by SnoepNFTs** [comment]
> If that works then VSCodium and this extension should work as well...

I am a bit unclear about the solution you are suggesting. I have already applied the open-remote-wsl extension by jeanp413 to my VSCodium setup to use WSL, but it didn't work, which is why I opened this issue.

To clarify, I have already downloaded both `wget` and `curl` in my linux distrubtions as instructed per the README.md requirements paragraph.

If there is something I am missing in your suggestion, please provide more details.

**Comment by GitMensch** [comment]
So with a recent VSCodium you still get the same "Error downloading server" (just with 1.91 in the URL)?

**Comment by SnoepNFTs** [comment]
> So with a recent VSCodium you still get the same "Error downloading server" (just with 1.91 in the URL)?

I have re-downloaded VSCodium and applied the "Open Remote WSL" extension by jeanp413 to my VSCodium setup to use WSL, and it worked!

I am unsure what caused the issue in the first place, as I do recall always having wget and curl on my Debian instance.

Anyway, I’m really happy that it works now. Thank you for following up with me, @GitMensch!
